sudo: false
os: linux
language: c

cache:
  ccache: true

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j4"

before_script:
  - wget https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz
  - tar xvf rocker_linux_amd64.tar.gz
  - rm rocker_linux_amd64.tar.gz
  - mkdir -p -m777 ~/.ccache

after_success:
  - if [[ -n "$DOCKER_USERNAME" && "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push ${DOCKER_IMAGE:-igalia/mesa}:${LLVM:+llvm-}${LLVM:-base};
    fi

script:
  - ./rocker build -f Rockerfile.llvm --var LLVM=$LLVM

jobs:
  include:
    - stage: Build Base
      script:
        - ./rocker build -f Rockerfile.base --var USE_TXC_DXTN=${USE_TXC_DXTN:-no}

    - stage: Build LLVM
      env: LLVM=3.3
    - env: LLVM=3.6
    - env: LLVM=3.8
    - env: LLVM=3.9
    - env: LLVM=4.0
