sudo: false
os: linux
services:
  - docker

env:
  global:
    - MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"

before_script:
  - pip install docker-jinja

script:
  - dj -d Dockerfile.base.jinja -o Dockerfile -e USE_TXC_DXTN=${USE_TXC_DXTN:-no} -e MAKEFLAGS=$MAKEFLAGS
  - docker build -t ${DOCKER_IMAGE:-mesa}:base .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.3
  - docker build -f Dockerfile -t ${DOCKER_IMAGE:-mesa}:llvm-3.3 .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.6
  - docker build -f Dockerfile -t ${DOCKER_IMAGE:-mesa}:llvm-3.6 .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.8
  - docker build -f Dockerfile -t ${DOCKER_IMAGE:-mesa}:llvm-3.8 .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.9
  - docker build -f Dockerfile -t ${DOCKER_IMAGE:-mesa}:llvm-3.9 .

after_success:
  - if [[ -n "$DOCKER_USERNAME" && "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push ${DOCKER_IMAGE:-mesa}:base;
      docker push ${DOCKER_IMAGE:-mesa}:llvm-3.3;
      docker push ${DOCKER_IMAGE:-mesa}:llvm-3.6;
      docker push ${DOCKER_IMAGE:-mesa}:llvm-3.8;
      docker push ${DOCKER_IMAGE:-mesa}:llvm-3.9;
    fi
