sudo: false
os: linux
services:
  - docker

branches:
  only:
    - master

script:
  - docker build -c 2 -f Dockerfile.base -t igalia/mesa:base .

after_success:
  - if [[ -n "$DOCKER_USERNAME" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push igalia/mesa:base;
    fi
