sudo: false
os: linux
services:
  - docker

env:
  global:
    - MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"

before_script:
  - pip install docker-jinja

script:
  - dj -d Dockerfile.base.jinja -o Dockerfile -e USE_TXC_DXTN=${USE_TXC_DXTN:-no} -e MAKEFLAGS=$MAKEFLAGS
  - docker build -t igalia/mesa:base .
  # - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.3 -e MAKEFLAGS=$MAKEFLAGS
  # - docker build -f Dockerfile -t igalia/mesa:llvm-3.3 .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.6 -e MAKEFLAGS=$MAKEFLAGS
  - docker build -f Dockerfile -t igalia/mesa:llvm-3.6 .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.8 -e MAKEFLAGS=$MAKEFLAGS
  - docker build -f Dockerfile -t igalia/mesa:llvm-3.8 .
  - dj -d Dockerfile.llvm.jinja -o Dockerfile -e LLVM=3.9 -e MAKEFLAGS=$MAKEFLAGS
  - docker build -f Dockerfile -t igalia/mesa:llvm-3.9 .

after_success:
  - if [[ -n "$DOCKER_USERNAME" && "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push igalia/mesa:base;
      docker push igalia/mesa:llvm-3.6;
      docker push igalia/mesa:llvm-3.8;
      docker push igalia/mesa:llvm-3.9;
    fi
