sudo: false
os: linux
language: c

cache:
  ccache: true
services:
  - docker

env:
  global:
    - MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"

before_script:
  - wget https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz
  - tar xvf rocker_linux_amd64.tar.gz
  - rm rocker_linux_amd64.tar.gz
  - mkdir -p -m777 ~/.ccache

script:
  - ./rocker build -f Rockerfile.base --var USE_TXC_DXTN=${USE_TXC_DXTN:-no}
  - ./rocker build -f Rockerfile.llvm --var LLVM=3.3
  - ./rocker build -f Rockerfile.llvm --var LLVM=3.6
  - ./rocker build -f Rockerfile.llvm --var LLVM=3.8
  - ./rocker build -f Rockerfile.llvm --var LLVM=3.9

after_success:
  - if [[ -n "$DOCKER_USERNAME" && "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push ${DOCKER_IMAGE:-igalia/mesa}:base;
      docker push ${DOCKER_IMAGE:-igalia/mesa}:llvm-3.6;
      docker push ${DOCKER_IMAGE:-igalia/mesa}:llvm-3.8;
      docker push ${DOCKER_IMAGE:-igalia/mesa}:llvm-3.9;
    fi
