#
# This builds and installs Shader-DB. Requires `docker-jinja`.
#
# ~~~
#  export MESA_RELEASE=master	# master, 17.0
#  dj -d Dockerfile.shader-db.jinja -o Dockerfile.shader-db -e RELEASE=$MESA_RELEASE
#  docker build . -f Dockerfile.shader-db -t igalia/mesa:shader-db
#  rm Dockefile.shader-db
# ~~~
#
# To run
#
#   `docker run --rm -v ~/my_results_dir/shader-db-$(date -u +%Y%m%d+%H%M):/results:Z --device=/dev/dri/renderD128 igalia/mesa:shader-db`
#

FROM igalia/mesa:{{ RELEASE }}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                              \
  && apt-get -y install python3 libepoxy-dev    \
  && rm -fr /var/lib/apt/lists/*

RUN git clone git://anongit.freedesktop.org/mesa/shader-db /root/shader-db

WORKDIR /root/shader-db

RUN git show --stat > /root/piglit-head.txt

RUN make

CMD [ "/bin/sh", "-c", "cp /root/*head.txt /results && ./run shaders > /results/results.txt" ]
