#
# This builds the base image for building Mesa.
#
# ~~~
#  dj -d Dockerfile.llvm.jinja -o Dockerfile       \
#    -e LLVM=3.3            # 3.3, 3.6, 3.8 or 3.9 \
#  docker build --pull -f Dockerfile -t igalia/mesa:{{ LLVM }} .
#  rm Dockerfile
# ~~~
#
# LLVM 3.3 package has been created with checkinstall using Base image
#
# ~~~
#  wget http://releases.llvm.org/3.3/llvm-3.3.src.tar.gz                                \
#    && tar xzpf llvm-3.3.src.tar.gz                                                    \
#    && cd llvm-3.3.src                                                                 \
#    && mkdir build                                                                     \
#    && cd build                                                                        \
#    && ../configure --enable-optimized --enable-shared --prefix=/usr/lib/llvm-3.3      \
#    && make                                                                            \
#    && echo "LLVM Toolchain 3.3" > description-pak                                     \
#    && checkinstall -D -y --pkgname=llvm-3.3 --pkgversion=3.3 --pkgrelease=+checkinstall1 --maintainer=jasuarez@igalia.com --provides=llvm
#  ~~~
#

FROM igalia/mesa:base

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

{% if LLVM == "3.9" %}
RUN apt-get update                                                            \
  && apt-get --no-install-recommends -y install gnupg                         \
  && wget -qO - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -     \
  && echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main" >> /etc/apt/sources.list  \
  && apt-get update                                                           \
  && apt-get --no-install-recommends -y install libclang-3.9-dev llvm-3.9-dev \
  && rm -fr /var/lib/apt/lists/*
{% elif LLVM == "3.8" %}
RUN apt-get update                                                            \
  && apt-get --no-install-recommends -y install libclang-3.8-dev llvm-3.8-dev \
  && rm -fr /var/lib/apt/lists/*
{% elif LLVM == "3.6" %}
RUN apt-get update                                                            \
  && apt-get --no-install-recommends -y install libclang-3.6-dev llvm-3.6-dev \
  && rm -fr /var/lib/apt/lists/*
{% elif LLVM == "3.3" %}
RUN wget https://people.igalia.com/jasuarez/packages/llvm-3.3_3.3-+checkinstall1_amd64.deb      \
  && dpkg -i llvm-3.3_3.3-+checkinstall1_amd64.deb                                              \
  && rm llvm-3.3_3.3-+checkinstall1_amd64.deb
{% endif %}
