#
# This builds the base image for building Mesa.
#
# ~~~
#  dj -d Dockerfile.llvm.jinja -o Dockerfile       \
#    -e LLVM=3.3            # 3.3, 3.6, 3.8 or 3.9 \
#    [-e MAKEFLAGS=-j2]     # -j2, -j4 ...
#  docker build --pull -f Dockerfile -t igalia/mesa:base .
#  rm Dockerfile
# ~~~
#

FROM igalia/mesa:base

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

{% if LLVM == "3.9" %}
RUN apt-get update                                                            \
  && apt-get --no-install-recommends -y install gnupg                         \
  && wget -qO - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -     \
  && echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main" >> /etc/apt/sources.list  \
  && apt-get update                                                           \
  && apt-get --no-install-recommends -y install libclang-3.9-dev llvm-3.9-dev \
  && rm -fr /var/lib/apt/lists/*
{% elif LLVM == "3.8" %}
RUN apt-get update                                                            \
  && apt-get --no-install-recommends -y install libclang-3.8-dev llvm-3.8-dev \
  && rm -fr /var/lib/apt/lists/*
{% elif LLVM == "3.6" %}
RUN apt-get update                                                            \
  && apt-get --no-install-recommends -y install libclang-3.6-dev llvm-3.6-dev \
  && rm -fr /var/lib/apt/lists/*
{% endif %}

{% if MAKEFLAGS %}
ENV MAKEFLAGS={{ MAKEFLAGS }}
{% endif %}

USER local

WORKDIR /home/local

{% if LLVM == "3.3" %}
RUN wget http://releases.llvm.org/3.3/llvm-3.3.src.tar.gz                             \
  && tar xzpf llvm-3.3.src.tar.gz                                                     \
  && rm llvm-3.3.src.tar.gz                                                           \
  && cd llvm-3.3.src                                                                  \
  && mkdir build                                                                      \
  && cd build                                                                         \
  && ../configure --enable-optimized --enable-shared --prefix=/usr/local/lib/llvm-3.3 \
  && make                                                                             \
  && sudo make install                                                                \
  && sudo rm -fr ../../llvm-3.3.src
{% endif %}

USER root
