#
# This builds and installs Mesa.
#
# ~~~
#  dj -d Dockerfile.mesa.jinja -o Dockerfile.mesa  \
#    -e BUILD=autotools	  # scons, autotools	   \
#    -e RELEASE=master	  # master, wip/17.0, wip/13.0
#    [-e BUILDJOBS=2]       # -j 2,3,... for make
#  docker build . -f Dockerfile.mesa -t igalia/mesa:master
#  rm Dockerfile.mesa
#

FROM igalia/mesa:base

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                                      \
  && apt-get -y --no-install-recommends install git     \
  && rm -fr /var/lib/apt/lists/*

{% if RELEASE == "master" %}
RUN git clone git://anongit.freedesktop.org/git/mesa/mesa /root/mesa
{% else %}
RUN git clone https://github.com/Igalia/release-mesa -b {{ RELEASE }} /root/mesa
{% endif %}

WORKDIR /root/mesa

RUN git show --stat > /root/mesa-head.txt

ENV PATH=/usr/lib/llvm-3.9/bin:$PATH

{% if BUILD == "scons" %}
RUN scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} llvm=1        \
  && scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} llvm=1 check \
  && rm -fr /root/mesa
{% else %}
RUN ./autogen.sh --with-egl-platforms=x11,drm,wayland                                           \
  --with-dri-drivers=i915,i965,radeon,r200,swrast,nouveau                                       \
  --with-gallium-drivers=i915,nouveau,r300,r600,freedreno,svga,swrast,vc4,virgl{% if "13.0" not in RELEASE %},etnaviv,imx{% endif %}    \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %}                                     \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} check                               \
  {% if RELEASE != "master" %} && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} distcheck {% endif %}                          \
  && make install                                                                               \
  && rm -fr /root/mesa
{% endif %}

WORKDIR /root
