#
# This builds and installs Mesa, master.
#
#   `docker build . -f Dockerfile-master -t jasuarez/mesa-release:master`
#

FROM jasuarez/mesa-release:base

MAINTAINER Juan A. Suarez Romero <jasuarez@igalia.com>

RUN apt-get update               \
  && apt-get -y install git      \
  && rm -fr rm -rf /var/lib/apt/lists/*

RUN git clone git://anongit.freedesktop.org/git/mesa/mesa /root/mesa

WORKDIR /root/mesa

RUN git show --stat > /root/mesa-head.txt

RUN ./autogen.sh --with-egl-platforms=x11,drm,wayland                                           \
  --with-dri-drivers=i915,i965,radeon,r200,swrast,nouveau                                       \
  --with-gallium-drivers=i915,nouveau,r300,r600,freedreno,svga,swrast,vc4,virgl,etnaviv,imx     \
  && make                                                                                       \
  && make check                                                                                 \
  && make install                                                                               \
  && rm -fr /root/mesa

WORKDIR /root
