#
# This builds and installs Piglit. Requires `docker-jinja`.
#
# ~~~
#  export MESA_RELEASE=master	# master, 17.0
#  dj -d Dockerfile.piglit.jinja -o Dockerfile.piglit -e RELEASE=$MESA_RELEASE
#  docker build . -f Dockerfile.piglit -t igalia/mesa:piglit
#  rm Dockerfile.piglit
# ~~~
#
# To run
#
#   `docker run --privileged --rm -t -v ~/my_results_dir/piglit-all-$(date -u +%Y%m%d+%H%M):/results:Z  -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix igalia/mesa:piglit`
#

FROM igalia/mesa:{{ RELEASE }}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                                                      \
  && apt-get -y install cmake libwaffle-dev libpng-dev libxkbcommon-dev \
    libglu1-mesa-dev libegl1-mesa-dev                                   \
  && rm -fr rm -rf /var/lib/apt/lists/*

RUN pip install numpy

RUN git clone git://anongit.freedesktop.org/piglit /root/piglit

WORKDIR /root/piglit

RUN git show --stat > /root/piglit-head.txt

RUN cmake . && make

CMD [ "/bin/sh", "-c", "cp /root/*head.txt /results && ./piglit-run.py tests/all -x texcombine -x texCombine /results" ]
