#
# This builds and installs Mesa.
#
# ~~~
#  dj -d Dockerfile.mesa.jinja -o Dockerfile.mesa       \
#    -e BUILD=autotools	  # scons, autotools, distcheck \
#    -e RELEASE=master	  # master, wip/17.0, wip/13.0
#    [-e BUILDJOBS=2]       # -j 2,3,... for make
#  docker build . -f Dockerfile.mesa -t igalia/mesa:master
#  rm Dockerfile.mesa
#

FROM igalia/mesa:base

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                                      \
  && apt-get -y --no-install-recommends install git     \
  && rm -fr /var/lib/apt/lists/*

USER local

{% if RELEASE == "master" %}
RUN git clone git://anongit.freedesktop.org/git/mesa/mesa /home/local/mesa
{% else %}
RUN git clone https://github.com/Igalia/release-mesa -b {{ RELEASE }} /home/local/mesa
{% endif %}

WORKDIR /home/local/mesa

RUN git show --stat > /home/local/mesa-head.txt

ENV PATH=/usr/lib/llvm-3.9/bin:$PATH

{% if BUILD == "scons" %}
RUN scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} llvm=1        \
  && scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} llvm=1 check \
  && sudo rm -fr /home/local/mesa
{% elif BUILD == "distcheck" %}
RUN ./autogen.sh                                                        \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} distcheck   \
  && sudo rm -fr /home/local/mesa
{% else %}
RUN ./autogen.sh --with-egl-platforms=x11,drm,wayland                           \
  --with-dri-drivers=i915,i965,radeon,r200,swrast,nouveau                       \
  --with-gallium-drivers=i915,nouveau,r300,r600,freedreno,svga,swrast,vc4,virgl{% if "13.0" not in RELEASE %},etnaviv,imx{% endif %}    \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %}                      \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} check                \
  && sudo make install                                                           \
  && sudo rm -fr /home/local/mesa
{% endif %}

USER root
