#
# This builds and installs Piglit. Requires `docker-jinja`.
#
# ~~~
#  dj -d Dockerfile.piglit.jinja -o Dockerfile        \
#    -e RELEASE=master   # master, 17.0, 13.0         \
#    [-e MAKEFLAGS=-j2]  # -j2, -j4 ...
#  docker build --pull -f Dockerfile -t igalia/mesa:piglit .
#  rm Dockerfile
# ~~~
#
# To run
#
# ~~~
#   mkdir -p -m 0777 ~/my_results_dir
#   docker run --privileged --rm -t -v ~/my_results_dir:/results:Z  -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix igalia/mesa:piglit
# ~~~
#

FROM igalia/mesa:{{ RELEASE }}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

USER root

RUN apt-get update                                                      \
  && apt-get -y --no-install-recommends install cmake libwaffle-dev     \
    libpng-dev libxkbcommon-dev libglu1-mesa-dev libegl1-mesa-dev       \
    python3-setuptools python3-pip                                      \
  && rm -fr /var/lib/apt/lists/*

RUN pip3 install numpy six mako

USER local

{% if MAKEFLAGS %}
ENV MAKEFLAGS={{ MAKEFLAGS }}
{% endif %}

WORKDIR /home/local

RUN wget -c https://raw.githubusercontent.com/tanty/mesa-resources/master/testing/full-piglit-run.sh

RUN chmod +x full-piglit-run.sh

RUN git clone --depth 1 git://anongit.freedesktop.org/piglit /home/local/piglit

WORKDIR /home/local/piglit

RUN git show --stat > /home/local/piglit-head.txt

VOLUME /results
