#
# This builds and installs Mesa, master.
#
#   `docker build . -f Dockerfile-shader-db -t jasuarez/mesa-release:shader-db`
#
# To run
#
#   `docker run --rm -v ~/my_results_dir/shader-db-$(date -u +%Y%m%d+%H%M):/results:Z --device=/dev/dri/renderD128 jasuarez/mesa-release:shader-db`
#

FROM jasuarez/mesa-release:master

MAINTAINER Juan A. Suarez Romero <jasuarez@igalia.com>

RUN apt-get update                              \
  && apt-get -y install python3 libepoxy-dev    \
  && rm -fr rm -rf /var/lib/apt/lists/*

RUN git clone git://anongit.freedesktop.org/mesa/shader-db /root/shader-db

WORKDIR /root/shader-db

RUN make

CMD [ "/bin/sh", "-c", "./run shaders > /results/results.txt" ]
