#
# This builds the base image for building Mesa.
#
# ~~~
#  dj -d Dockerfile.base.jinja -o Dockerfile.base       \
#    [-e LLVM=3.3]          # 3.3, 3.6, 3.8 or 3.9      \
#    [-e BUILDJOBS=2]       # -j 2,3,... for make
#  docker build [--pull] -f Dockerfile.base -t igalia/mesa:base .
#

{% if LLVM %}
FROM igalia/mesa:base
{% else %}
FROM debian:unstable
{% endif %}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"


{% if not LLVM %}
RUN apt-get update                                                                     \
  && apt-get --no-install-recommends -y install autoconf gcc g++ sudo cmake patch      \
    automake pkg-config libtool-bin bison flex python-pip libpthread-stubs0-dev        \
    wget libxau-dev libx11-dev libxext-dev libxdamage-dev libx11-xcb-dev gettext       \
    zlib1g-dev scons libelf-dev libxvmc-dev libvdpau-dev libva-dev libclc-dev          \
    libpciaccess-dev libxxf86vm-dev python-setuptools python-wheel bzip2 make          \
    mesa-common-dev libxcb-dri3-dev libxcb-present-dev libxcb-glx0-dev xutils-dev      \
    libxcb-dri2-0-dev libexpat1-dev xz-utils                                           \
  && rm -fr /var/lib/apt/lists/*

RUN pip install mako

RUN adduser --gecos "" local && passwd -d local && adduser local sudo
{% endif %}

USER local

WORKDIR /home/local

{% if LLVM == "3.3" %}
RUN wget http://releases.llvm.org/3.3/llvm-3.3.src.tar.gz                                                                                                                     \
  && tar xzpf llvm-3.3.src.tar.gz                                                                                                                                             \
  && rm llvm-3.3.src.tar.gz                                                                                                                                                   \
  && wget 'http://llvm.org/viewvc/llvm-project/llvm/trunk/lib/Target/AArch64/Utils/CMakeLists.txt?r1=174369&r2=182190&pathrev=182190&sortby=rev&view=patch' -O llvm-3.3.patch \
  && cd llvm-3.3.src                                                                                                                                                          \
  && patch -p2 -i ../llvm-3.3.patch                                                                                                                                           \
  && rm ../llvm-3.3.patch                                                                                                                                                     \
  && mkdir build                                                                                                                                                              \
  && cd build                                                                                                                                                                 \
  && cmake ../ -G "Unix Makefiles" -DLLVM_BUILD_LLVM_DYLIB=ON -DCMAKE_INSTALL_PREFIX=/usr/local/lib/llvm-3.3 -DCMAKE_BUILD_TYPE=Release                                       \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                                                                                                      \
  && sudo rm -fr ../../llvm-3.3.src
{% elif LLVM == "3.6" %}
RUN wget http://releases.llvm.org/3.6.2/llvm-3.6.2.src.tar.xz                                                                           \
  && tar xJpf llvm-3.6.2.src.tar.xz                                                                                                     \
  && rm llvm-3.6.2.src.tar.xz                                                                                                           \
  && cd llvm-3.6.2.src                                                                                                                  \
  && mkdir build                                                                                                                        \
  && cd build                                                                                                                           \
  && cmake ../ -G "Unix Makefiles" -DLLVM_BUILD_LLVM_DYLIB=ON -DCMAKE_INSTALL_PREFIX=/usr/local/lib/llvm-3.6 -DCMAKE_BUILD_TYPE=Release \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                                                                \
  && sudo rm -fr ../../llvm-3.6.2.src
{% elif LLVM == "3.8" %}
RUN wget http://releases.llvm.org/3.8.1/llvm-3.8.1.src.tar.xz                                                                           \
  && tar xJpf llvm-3.8.1.src.tar.xz                                                                                                     \
  && rm llvm-3.8.1.src.tar.xz                                                                                                           \
  && cd llvm-3.8.1.src                                                                                                                  \
  && mkdir build                                                                                                                        \
  && cd build                                                                                                                           \
  && cmake ../ -G "Unix Makefiles" -DLLVM_BUILD_LLVM_DYLIB=ON -DCMAKE_INSTALL_PREFIX=/usr/local/lib/llvm-3.8 -DCMAKE_BUILD_TYPE=Release \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                                                                \
  && sudo rm -fr ../../llvm-3.8.1.src
{% elif LLVM == "3.9" %}
RUN wget http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz                                                                           \
  && tar xJpf llvm-3.9.1.src.tar.xz                                                                                                     \
  && rm llvm-3.9.1.src.tar.xz                                                                                                           \
  && cd llvm-3.9.1.src                                                                                                                  \
  && mkdir build                                                                                                                        \
  && cd build                                                                                                                           \
  && cmake ../ -G "Unix Makefiles" -DLLVM_BUILD_LLVM_DYLIB=ON -DCMAKE_INSTALL_PREFIX=/usr/local/lib/llvm-3.9 -DCMAKE_BUILD_TYPE=Release \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                                                                \
  && sudo rm -fr ../../llvm-3.9.1.src
{% else %}
RUN wget http://xorg.freedesktop.org/releases/individual/proto/glproto-1.4.14.tar.bz2   \
  && tar -jxvf glproto-1.4.14.tar.bz2                                                   \
  && rm glproto-1.4.14.tar.bz2                                                          \
  && cd glproto-1.4.14                                                                  \
  && ./configure                                                                        \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                \
  && sudo rm -fr ../glproto-1.4.14

RUN wget http://xorg.freedesktop.org/releases/individual/proto/dri2proto-2.8.tar.bz2    \
  && tar -jxvf dri2proto-2.8.tar.bz2                                                    \
  && rm dri2proto-2.8.tar.bz2                                                           \
  && cd dri2proto-2.8                                                                   \
  && ./configure                                                                        \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                \
  && sudo rm -fr ../dri2proto-2.8

RUN wget http://xorg.freedesktop.org/releases/individual/proto/dri3proto-1.0.tar.bz2    \
  && tar -jxvf dri3proto-1.0.tar.bz2                                                    \
  && rm dri3proto-1.0.tar.bz2                                                           \
  && cd dri3proto-1.0                                                                   \
  && ./configure                                                                        \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                \
  && sudo rm -fr ../dri3proto-1.0

RUN wget http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.0.tar.bz2 \
  && tar -jxvf presentproto-1.0.tar.bz2                                                 \
  && rm presentproto-1.0.tar.bz2                                                        \
  && cd presentproto-1.0                                                                \
  && ./configure                                                                        \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                \
  && sudo rm -fr ../presentproto-1.0

# RUN wget http://xcb.freedesktop.org/dist/xcb-proto-1.11.tar.bz2          \
#   && tar -jxvf xcb-proto-1.11.tar.bz2                                    \
#   && rm xcb-proto-1.11.tar.bz2                                           \
#   && cd xcb-proto-1.11                                                   \
#   && ./configure                                                         \
#   && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install \
#   && sudo rm -fr ../xcb-proto-1.11

# RUN wget http://xcb.freedesktop.org/dist/libxcb-1.11.tar.bz2             \
#   && tar -jxvf libxcb-1.11.tar.bz2                                       \
#   && rm libxcb-1.11.tar.bz2                                              \
#   && cd libxcb-1.11                                                      \
#   && ./configure                                                         \
#   && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install \
#   && sudo rm -fr ../libxcb-1.11

RUN wget http://xorg.freedesktop.org/releases/individual/lib/libxshmfence-1.1.tar.bz2   \
  && tar -jxvf libxshmfence-1.1.tar.bz2                                                 \
  && rm libxshmfence-1.1.tar.bz2                                                        \
  && cd libxshmfence-1.1                                                                \
  && ./configure                                                                        \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                \
  && sudo rm -fr ../libxshmfence-1.1

RUN wget https://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.bz2   \
  && tar -jxvf libtxc_dxtn-1.0.1.tar.bz2                                                \
  && rm libtxc_dxtn-1.0.1.tar.bz2                                                       \
  && cd libtxc_dxtn-1.0.1                                                               \
  && ./configure                                                                        \
  && sudo make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} install                \
  && sudo rm -fr ../libtxc_dxtn-1.0.1
{% endif %}

USER root
