#
# This builds and installs Mesa.
#
# ~~~
#  dj -d Dockerfile.mesa.jinja -o Dockerfile.mesa                \
#    -e BUILD=autotools	  # scons, autotools, windows, distcheck \
#    -e BUILDJOBS=2       # -j 2,3,... for make                  \
#    -e LLVM=3.3          # 3.3, 3.6, 3.8 or 3.9                 \
#    [-e RELEASE=master]  # master, wip/17.0, wip/13.0
#  docker build --pull -f Dockerfile.mesa -t igalia/mesa:llvm-{{ LLVM }} .
#  rm Dockerfile.mesa
#

{% if BUILD == "windows" %}
FROM igalia/mesa:base
{% else %}
FROM igalia/mesa:llvm-{{ LLVM }}
{% endif %}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                                   \
  && apt-get -y --no-install-recommends install git  \
     {% if BUILD == "windows" %}mingw-w64{% endif %} \
  && rm -fr /var/lib/apt/lists/*

USER local

{% if RELEASE %}
RUN git clone https://github.com/Igalia/release-mesa --depth 1 -b {{ RELEASE }} /home/local/mesa
{% else %}
ADD . /home/local/mesa
RUN sudo chown -R local:local /home/local/mesa
{% endif %}

WORKDIR /home/local

RUN export DRM_VERSION=`cat /home/local/mesa/configure.ac | egrep ^LIBDRM.*REQUIRED| cut -f2 -d= | sort -nr | head -n 1`        \
  && wget http://dri.freedesktop.org/libdrm/libdrm-$DRM_VERSION.tar.bz2              \
  && tar -jxvf libdrm-$DRM_VERSION.tar.bz2                                           \
  && rm libdrm-$DRM_VERSION.tar.bz2                                                  \
  && cd libdrm-$DRM_VERSION                                                          \
  && ./configure --enable-freedreno --enable-vc4 --enable-etnaviv-experimental-api   \
  && sudo make install                                                               \
  && sudo rm -fr ../libdrm-$DRM_VERSION                                              \
  && unset DRM_VERSION

WORKDIR /home/local/mesa

RUN git show --stat > /home/local/mesa-head.txt

{% if LLVM|float >= 3.8 %}
ENV PATH=/usr/lib/llvm-{{ LLVM }}/bin:$PATH
{% else %}
ENV PATH=/usr/local/lib/llvm-{{ LLVM }}/bin:$PATH
{% endif %}

{% if BUILD == "scons" %}
RUN scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} llvm=1        \
  && scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} llvm=1 check \
  && sudo rm -fr /home/local/mesa
{% elif BUILD == "windows" %}
RUN scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} platform=windows toolchain=crossmingw        \
  && scons {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} platform=windows toolchain=crossmingw check \
  && sudo rm -fr /home/local/mesa
{% elif BUILD == "distcheck" %}
RUN ./autogen.sh                                                        \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} distcheck   \
  && sudo rm -fr /home/local/mesa
{% else %}
RUN ./autogen.sh --with-egl-platforms=x11,drm,wayland                           \
  --with-dri-drivers=i915,i965,radeon,r200,swrast,nouveau                       \
  --with-gallium-drivers=i915,nouveau,r300{% if LLVM|float >= 3.8 %},r600,radeonsi{% endif %},freedreno,svga,swrast{% if LLVM|float >= 3.9 %},swr{% endif %},vc4,virgl{% if "13.0" not in RELEASE %},etnaviv,imx{% endif %}    \
  --with-vulkan-drivers=intel{% if LLVM|float >= 3.9 %},radeon{% endif %}       \
  --enable-llvm --enable-llvm-shared-libs                                       \
  --enable-glx-tls --enable-gbm --enable-egl                                    \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %}                     \
  && make {% if BUILDJOBS %} -j {{ BUILDJOBS }} {% endif %} check               \
  && sudo make install                                                          \
  && sudo rm -fr /home/local/mesa
{% endif %}

WORKDIR /home/local

USER root
