#
# This builds and installs Shader-DB. Requires `docker-jinja`.
#
# ~~~
#  dj -d Dockerfile.shader-db.jinja -o Dockerfile.shader-db \
#    -e VIDEO_GID=`getent group video | cut -f3 -d:`        \
#    -e RELEASE=master   # master, 17.0, 13.0
#  docker build . --pull -f Dockerfile.shader-db -t igalia/mesa:shader-db
#  rm Dockefile.shader-db
# ~~~
#
# To run
#
# ~~~
#   mkdir -p -m 0777 ~/my_results_dir
#   docker run --rm -v ~/my_results_dir:/results:Z --device=/dev/dri/renderD128 igalia/mesa:shader-db
# ~~~
#

FROM igalia/mesa:{{ RELEASE }}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                                      \
  && apt-get -y --no-install-recommends install python3 \
  libepoxy-dev                                          \
  && rm -fr /var/lib/apt/lists/*

# {{ VIDEO_GID }} is the gid for outside's video group. Required to access to
# /dev/dri/renderD128
RUN usermod -G {{ VIDEO_GID }} -a local

USER local

RUN git clone --depth 1 git://anongit.freedesktop.org/mesa/shader-db /home/local/shader-db

WORKDIR /home/local/shader-db

RUN git show --stat > /home/local/piglit-head.txt

RUN make

VOLUME /results

CMD [ "/bin/sh", "-c", "cp /home/local/*head.txt /results && ./run shaders > /results/results.txt" ]
