#
# This builds and installs Piglit. Requires `docker-jinja`.
#
# ~~~
#  dj -d Dockerfile.piglit.jinja -o Dockerfile        \
#    -e RELEASE=master   # master, 17.0, 13.0         \
#  docker build --pull -t igalia/mesa:piglit .
#  rm Dockerfile
# ~~~
#
# To run
#
# ~~~
#   mkdir -p -m 0777 ~/my_results_dir
#   docker run --privileged --rm -t -v ~/my_results_dir:/results:Z  -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix igalia/mesa:piglit
# ~~~
#

FROM igalia/mesa:{{ RELEASE }}

LABEL maintainer "Juan A. Suarez Romero <jasuarez@igalia.com>"

RUN apt-get update                                                      \
  && apt-get -y --no-install-recommends install cmake libwaffle-dev     \
    libpng-dev libxkbcommon-dev libglu1-mesa-dev libegl1-mesa-dev       \
  && rm -fr /var/lib/apt/lists/*

RUN pip install numpy six

USER local

ENV MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"

RUN git clone --depth 1 git://anongit.freedesktop.org/piglit /home/local/piglit

WORKDIR /home/local/piglit

RUN git show --stat > /home/local/piglit-head.txt

RUN cmake . && make $MAKEFLAGS

VOLUME /results

CMD [ "/bin/sh", "-c", "cp /home/local/*head.txt /results && ./piglit-run.py tests/all -x texcombine -x texCombine /results" ]
